### GET request to example server
GET localhost:8080/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcHQiOiJhYjg5ZWJiNDRmNzA0NTAyMmI3MWNiYjg4NjdkMjAwMGM1NzA3ZjgxNjYyOWQ1NDM3YjlmOGFhZWZhMTYwYTAxIiwiaXNzIjoidGVzdCIsImF1ZCI6WyJ0ZXN0Il0sImV4cCI6MTcyODA2Njg5NywiaWF0IjoxNzI4MDYzMjk3LCJqdGkiOiI0MzMzNDhmYi1mODVjLTQ5MzItYjEzMy02OTVlMWU1NDUxNDMifQ.QudRFbPtNnpqho_w9jyqhffhiMZXfAmlERgOEsUhjck
Cookie: fingerprint=076d2a1ab6195f14ccd4e046d80edd1344d44234921ed29f91116a66fb16ef0d
###